# Generated by Django 4.1.9 on 2023-05-20 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(default='', max_length=36)),
                ('age', models.IntegerField(default='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NA', 'Prefer not to say')], default='', max_length=10)),
                ('contactNumber', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True)),
                ('beginnerAtYoga', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=5)),
                ('purpose', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('ailment', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('packageSelection', models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly')], default='M', max_length=5)),
                ('batchTimingSelection', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], default='', max_length=10)),
                ('paymentMode', models.CharField(choices=[('U', 'UPI'), ('A', 'Transfer to account')], default='U', max_length=10)),
                ('paymentStatus', models.CharField(choices=[('P', 'Processed'), ('U', 'Unpaid')], default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
