# Generated by Django 5.2.4 on 2025-09-11 07:02

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        choices=[
                            ("+44", "United Kingdom"),
                            ("+91", "India"),
                            ("+1", "United States"),
                            ("+31", "Netherlands"),
                            ("+49", "Germany"),
                            ("+33", "France"),
                            ("+39", "Italy"),
                            ("+34", "Spain"),
                        ],
                        max_length=5,
                    ),
                ),
                ("currency_symbol", models.CharField(default="₹", max_length=5)),
                ("discount", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "weekend_flow_price_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "personalized_flow_price_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "morning_monthly_price_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "morning_quarterly_price_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "regular_monthly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "regular_quarterly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "personalized_sessions",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("weekend_flow", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "batch_timing1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "batch_timing2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="", max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                ("country_code", models.CharField(default="+91", max_length=5)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrialClassUserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_num",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="", max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "focus_choices",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                (
                    "style_choices",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing_page.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YogaUserMorning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_choice", models.CharField(default="Batch I", max_length=10)),
                ("date_of_joining", models.CharField(default="", max_length=25)),
                (
                    "profile",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing_page.profile",
                    ),
                ),
            ],
        ),
    ]
