# Generated by Django 4.1.9 on 2023-05-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001F5A62BD2D0>', max_length=200),
        ),
    ]
